---
- hosts: websever
  tasks:
   - name: change permission
      shell: sudo chmod /var/run/docker.sock  
    - name: login to jfrog
      shell: docker login -u ranjuranju5416@gmail.com -p Sarvikarn@5416 personal54.jfrog.io   
    
    - name: pull an image
      shell: docker pull personal54.jfrog.io/docker-cicd/dockerimgname:{{ BUILD_NUMBER }}

    #- name: remove container
     # shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 personal54.jfrog.io/docker-cicd/dockerimgname:{{ BUILD_NUMBER }}
 
   
